In [1]:
# Imports
import time
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# PyTorch libraries
import torch
from torch import nn
from torch.utils.data import DataLoader

In [2]:
mps_compiled = torch.backends.mps.is_built()
mps_available = torch.backends.mps.is_available()
print(f"MPS compiled: {mps_compiled}. MPS available: {mps_available}")


MPS compiled: True. MPS available: True


# Pytorch Basics

In [5]:
# Some basic initializers
a = torch.tensor([1, 2, 3])
b = torch.tensor(((1, 2, 3), (3, 4, 5)))
c = torch.ones(3, 4)
d = torch.empty(2, 2, 3)
print(a)
print(b)
print(c)
print(d)

# With distributions
e = torch.rand(1, 2)
f = torch.randn(1, 2)
print(e)
print(f)

# Ranges
g = torch.arange(1, 10, step = 1)
h = torch.linspace(0, 1, steps = 10)
print(g)
print(h)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [3, 4, 5]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[0.6469, 0.3336]])
tensor([[-0.2468, -0.1294]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [6]:
A = torch.ones(20, 21)
Z = np.vander([1, 2, 3], 4)
B = torch.tensor(Z)
C = torch.rand_like(A)
D = torch.arange(4, 41, step = 2)
print(A)
print(B)
print(C)
print(D)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 

# Basic matrix multiplication and addition 

In [7]:
a1 = torch.tensor(((2, 4), (5, 7)))
a2 = torch.tensor(((1, 1), (2, 3)))
a3 = torch.tensor(((10, 10), (12, 1)))
print((a1 @ a2) + a3)

tensor([[20, 24],
        [31, 27]])


In [8]:
b1 = torch.tensor((3, 5, 7))
b2 = torch.tensor((2, 4, 8))
torch.dot(b1, b2)

tensor(82)

## Indexing and Reshaping

In [9]:
a = torch.arange(0, 10, step=1)
print(a[-1])
print(a[0:5])
print(a[1:9:2])

b = torch.rand(2, 2, 2, 2)
print(b[0].shape)
print(b[0][0].shape)
print(b[0][0][0].shape)

c = torch.arange(0, 10)
print(c.reshape(2, 5))
print(c.reshape(5, 2))
d = c.reshape(5, 2)
print(d.flatten())

tensor(9)
tensor([0, 1, 2, 3, 4])
tensor([1, 3, 5, 7])
torch.Size([2, 2, 2])
torch.Size([2, 2])
torch.Size([2])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Squezing
Removes redundant dimensions from a Tensor

In [10]:
a = torch.rand(2, 1, 4, 1)
print(a.shape)
b = a.squeeze()
print(b.shape)

torch.Size([2, 1, 4, 1])
torch.Size([2, 4])


# Concatenation

In [11]:
a = torch.arange(12).reshape(3, 4)
b = torch.ones(3, 4)
d = torch.cat((a, b), dim=0) # Along the columns
e = torch.cat((a, b), dim=1) # Along the rows
print(d)
print(e)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
        [ 4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.],
        [ 8.,  9., 10., 11.,  1.,  1.,  1.,  1.]])


In [12]:
x = torch.arange(1, 5)
y = x.numpy()
z = torch.tensor(y)
print(x, y, z)

tensor([1, 2, 3, 4]) [1 2 3 4] tensor([1, 2, 3, 4])


In [13]:
def sum_a(t1: torch.tensor, t2: torch.tensor):
    return torch.sum(t1, dim=0) * torch.sum(t2)

a = torch.tensor(((1, 1,), (1, 1)))
b = torch.tensor(((1, 2, 3), (1, 2, 3)))
print(sum_a(a, b))

def sum_b(t: torch.tensor):
    a = t.flatten()
    size = a.shape[0]
    b = torch.arange(size)
    return torch.concat((b.reshape(size, 1), a.reshape(size, 1)), dim=1)

a = torch.tensor([[2, 3], [-1, 10]])
b = torch.tensor(1)
print(sum_b(a))
print(sum_b(b))

def sum_c(t1: torch.tensor, t2: torch.tensor):
    if torch.numel(t2) == torch.numel(t1): # Can t2 be re-shaped into t1's shape
        t2_re = t2.reshape(t1.shape)
        return t1 + t2_re
    else:
        return torch.concat((t1.flatten(), t2.flatten()))
    
a = torch.tensor([[1, -1], [-1, 3]])
b = torch.tensor([2, 3, 0, 2])
c = torch.tensor([2, 3, 0])
print(sum_c(a, b))
print(sum_c(a, c))
        


tensor([24, 24])
tensor([[ 0,  2],
        [ 1,  3],
        [ 2, -1],
        [ 3, 10]])
tensor([[0, 1]])
tensor([[ 3,  2],
        [-1,  5]])
tensor([ 1, -1, -1,  3,  2,  3,  0])


# Working with GPUs

In [14]:
# Where does the variable live?
x = torch.randn(10)
print(x.device)

cpu


In [15]:
print(f"Is cuda available? {torch.cuda.is_available()}") 
print(f"Is MPS available? {torch.backends.mps.is_available()}")

mps = torch.device("mps")
x = torch.randn(10, device=mps)
print(x)

Is cuda available? False
Is MPS available? True
tensor([-1.5406,  0.5549,  1.0488,  0.7012,  1.1588, -1.2191, -0.5871, -2.2900,
        -0.6908, -0.1875], device='mps:0')


In [16]:
# Cannot work with variables across CPU and GPU

x = torch.randn(10, device=mps)
y = torch.randn(10)
print(x.device)
print(y.device)
print(x+y)


mps:0
cpu


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

Moving a variable from the cpu to gpu  

In [ ]:
a = torch.tensor([0, 1, 2], device="mps")
b = torch.tensor([3, 4, 5], device="cpu")
print(a + b.to("mps")) 
print(a.to("cpu") + b)

## How much faster is the GPU than the CPU?

In [ ]:
import time

def test_gpu_v_cpu(dim, device):
    # We synchronize the PyTorch kernel ops for a fair assessment of performance
    torch.mps.synchronize()
    x = torch.rand(dim, dim, device=device)
    y = torch.rand(dim, dim, device=device)
    z = torch.ones(dim, dim, device=device) * 2
    
    a = x + y
    b = x @ z
    torch.mps.synchronize()
    return a, b
    
def time_fn(fn, iterations) -> float:
    start = time.perf_counter()
    print(f"running timer for {iterations} iterations")
    for i in range(iterations):
        fn()
    end = time.perf_counter()
    return end - start

# Perform operations on high dimensional tensors (i.e 1000 x 1000)
print(time_fn(lambda: test_gpu_v_cpu(1000, "mps"), 100))
print(time_fn(lambda: test_gpu_v_cpu(1000, "cpu"), 100))



## Datasets and Dataloaders

In [3]:
from torchvision import datasets
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
from torchvision.transforms import Compose, Grayscale